### ISSUE TITLE
Auto Inference should keep original column names

### ISSUE THREAD

**Issue by kaklakariada** [exasol/virtual-schema-common-document-files#163]
See issue https://github.com/exasol/virtual-schema-common-document/issues/189:

> Auto inference should have an option keep the original column names instead of always changing them to UPPER_SNAKE_CASE. The conversion is only mentioned for CSV files, so it happening for Parquet files also may be a bug.

**Comment by tm-henningnt** [comment]
Works great, thanks for adding!

**Comment by kaklakariada** [comment]
Happy to hear that, thanks for your feedback :-)
